---
title: "主成分分析・因子分析"
author: "藤野秀則"
date: 
  初稿日:"2024-10-15"
  更新日:`r Sys.Date()`
output:
  html_document: 
    toc: true
    toc_depth: 4
    toc_float: true
    number_section: true
    fig_width: 8
    css: ./style.css
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

取得したデータの変数が多い場合（**多変量データ**と呼ぶ）に，それら1つ1つの変数を分析するのは非常に骨が折れる作業になる．そういう場合には，「似たようなデータ」になっているものを集約して，もとの変数よりも少ない数の集約変数で分析するのが効率的である．

そのような変数の集約をするための分析が主成分分析（PCA: Principal Component Analysis）と因子分析（FA: Factor Analysis）である．



# 主成分分析（PCA）

さて変数を集約するときにどのように集約するべきだろうか．単純にそれぞれの得点を合計したり平均値にしたりする方法が真っ先に思い浮かぶ．
しかし，それは妥当な方法だろうか？

例えば，中学や高校の定期テストの総合的な成績を評価する際には，単純に各科目の点数を足し合わせた合計得点，総合的な成績を評価することが多い．しかし，単純な合計点で総合的な成績を評価するのは妥当だろうか？

例えば中学や高校での定期テストの総合的な成績を評価することを考えてみよう．
平均点が45点で標準偏差が10点の数学で80点を取っている人，
平均点が85点で標準偏差が10点の英語で80点を取っている人，
つまり，数学は難易度が高いテストであり，英語は難易度が低いテスト，国語は難易度が中程度のテストだったということである．数学での80点は英語や国語の80点よりもはるかに価値が高い得点のはずであるが，単純に合計得点で総合成績を評価するということは，これらの科目の間の難易度の違いを考慮していないことになる．

実際には科目によって難易度は異なっているため，難易度が高い問題が多く出された科目では多くの人が低い得点となるため，平均点もばらつきも低くなりやすいし，難易度が低い問題が多く出された科目は多くの人が高い得点となるため，平均点は高く，ばらつきは低くなりやすい．難易度が高い問題と低い問題が適度に出されていた場合には，平均点もばらつきも中程度になる．このようなときに，このとき，数学と英語の点数は平均点からの差が同じであるが，国語の点数は平均点からの差が大きい．このような場合には，数学と英語の点数は似たようなデータであるといえるが，国語の点数は異なるデータであるといえる．

